apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-mysql
  labels:
    app: {{ template "name" . }}-mysql
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  MYSQL_ROOT_PASSWORD: {{ default "root123" .Values.mysql.rootPassword | quote }}
