apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-jobservice
  labels:
    app: {{ template "name" . }}-jobservice
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.jobservice.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-jobservice
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: jobservice-app
        image: {{ .Values.jobservice.image.repository }}:{{ .Values.jobservice.image.tag }}
        imagePullPolicy: {{ .Values.jobservice.image.pullPolicy }}
        resources:
{{ toYaml .Values.jobservice.resources | indent 10 }}
        env:
          - name: MYSQL_HOST
            valueFrom: 
              configMapKeyRef: 
               name: {{ template "name" . }}-jobservice
               key: MYSQL_HOST
          - name: MYSQL_PORT
            valueFrom: 
              configMapKeyRef: 
               name: {{ template "name" . }}-jobservice
               key: MYSQL_PORT
          - name: MYSQL_USR
            valueFrom: 
              configMapKeyRef: 
               name: {{ template "name" . }}-jobservice
               key: MYSQL_USR
          - name: MYSQL_PWD
            valueFrom: 
              configMapKeyRef: 
               name: {{ template "name" . }}-jobservice
               key: MYSQL_PWD
          - name: UI_SECRET
            valueFrom: 
              configMapKeyRef: 
               name: {{ template "name" . }}-jobservice
               key: UI_SECRET
          - name: SECRET_KEY
            valueFrom: 
              configMapKeyRef: 
               name: {{ template "name" . }}-jobservice
               key: SECRET_KEY
          - name: CONFIG_PATH
            valueFrom: 
              configMapKeyRef: 
               name: {{ template "name" . }}-jobservice
               key: CONFIG_PATH
          - name: REGISTRY_URL
            valueFrom: 
              configMapKeyRef: 
               name: {{ template "name" . }}-jobservice
               key: REGISTRY_URL
          - name: VERIFY_REMOTE_CERT
            valueFrom: 
              configMapKeyRef: 
               name: {{ template "name" . }}-jobservice
               key: VERIFY_REMOTE_CERT
          - name: MAX_JOB_WORKERS
            valueFrom: 
              configMapKeyRef: 
               name: {{ template "name" . }}-jobservice
               key: MAX_JOB_WORKERS
          - name: LOG_LEVEL
            valueFrom: 
              configMapKeyRef: 
               name: {{ template "name" . }}-jobservice
               key: LOG_LEVEL
          - name: LOG_DIR
            valueFrom: 
              configMapKeyRef: 
               name: {{ template "name" . }}-jobservice
               key: LOG_DIR
          - name: GODEBUG
            valueFrom: 
              configMapKeyRef: 
               name: {{ template "name" . }}-jobservice
               key: GODEBUG
          - name: EXT_ENDPOINT
            valueFrom: 
              configMapKeyRef: 
               name: {{ template "name" . }}-jobservice
               key: EXT_ENDPOINT
          - name: TOKEN_URL
            valueFrom: 
              configMapKeyRef: 
               name: {{ template "name" . }}-jobservice
               key: TOKEN_URL
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/jobservice
        - name: logs
          mountPath: /var/log/jobs
      volumes:
      - name: config
        configMap:
          name: {{ template "name" . }}-jobservice
          items:
          - key: config
            path: app.conf
      - name: logs
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-log 
